### ISSUE TITLE
How can we easily deploy Dockers in production?

### ISSUE THREAD

**Issue by osakatand** [gitlinks/github-rank-project#21]
Openshift? Or something else?
It should be easy to deploy and to use.

**Comment by callicles** [comment]
Pricing for openshift containers on the red hat cloud just came out. It is far to expensive. If we can have resources for free that would be nice. Otherwise I think that's a no go.

Another solution for using containers 
https://cloud.google.com/container-engine/ Pricing looks reasonable.

They seems to have figured out storage for dbs in containers.

**Comment by osakatand** [comment]
For now we'll deploy dockers manually, we'll look into google cloud or other one a later (we don't want to depend on an external service).
